name: tor-mkg20001
version: tor-0.4.1.6
summary: Defend yourself against network surveillance and traffic analysis
description: |
  Tor is free software and an open network that helps you defend
  against traffic analysis, a form of network surveillance
  that threatens personal freedom and privacy, confidential
  business activities and relationships, and state security.

grade: stable
confinement: strict

apps:
  tor:
    command: bin/tor
    plugs: [network,network-bind]
    aliases:
      - tor
  gencert:
    command: bin/tor-gencert
  resolve:
    command: bin/tor-resolve
    plugs: [network]
    aliases:
      - tor-resolve
  torify:
    command: bin/torify
    plugs: [network,network-bind]
    aliases:
      - torify

parts:
  tor:
    source: https://git.torproject.org/tor.git
    source-tag: tor-0.4.1.6
    source-type: git
    plugin: autotools
    configflags: [--disable-asciidoc]
    build-packages:
      - git
      - build-essential
      - automake
      - libevent-dev
      - libssl-dev
